{"name": "test_edit_clean_files", "status": "broken", "statusDetails": {"message": "UnboundLocalError: local variable 'result' referenced before assignment", "trace": "self = <Test_Application.Test_Application object at 0x000002372129C670>\n\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_edit_clean_files(self):\n        ####\n        # Test the function of application to check clean files that were changed\n        # ###\n>       results = mngtests.test_EditCleanFiles()\n\nC:\\Baruch\\Alot\\WorkSpace\\Test_Application.py:90: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Automation.Manag_Tests.Manag_Tests object at 0x0000023721266A00>\n\n    @allure.severity(allure.severity_level.NORMAL)\n    def test_EditCleanFiles(self):\n        ###\n        # Second test that copy all files that generate in test 1 and look on the test application screen\n        # and collect the data\n        # ###\n        num = 10\n        self.addreportline(\"3. Test Edit Clean Files\")\n        self.addlogline(\" Start Edit Clean {0} Files in Watch Directory\".format(num))\n        self.mngproccess.CleardOutArray()\n        # Edit 10 clean files and look on the results from the application\n        cahngedfiles = self.generatTests.EditSeveralCleanFile(num)\n        time.sleep(10)\n        passtest,results = self.TestChengesFiles(self.mngproccess.GetStdOutArray(),num,cahngedfiles)\n        if  passtest:\n            self.addreportline(\"3.1 PASS Change {0} Clean Files\".format(num))\n            self.addlogline(\"Pass Change {0} Clean Files\".format(num))\n        else:\n            result = False\n            self.addreportline(\"3.1 FAIL Change {0} Clean Files\".format(num))\n            self.addlogline(\"Fail Change {0} Clean Files\".format(num))\n            count = 1\n            for i in results:\n                self.addreportline(\" 3.1.{0} {1}\".format(count, i))\n                count += 1\n    \n>       return result\nE       UnboundLocalError: local variable 'result' referenced before assignment\n\nC:\\Baruch\\Alot\\WorkSpace\\Automation\\Manag_Tests.py:138: UnboundLocalError"}, "start": 1603906663429, "stop": 1603906678608, "uuid": "0f00e4d1-e512-4c0e-8101-915246f3dd05", "historyId": "afb98bae313e5fa969e829db8cfddd97", "testCaseId": "3240cc93d95b8b4ccf278555bc9d850a", "fullName": "Test_Application.Test_Application#test_edit_clean_files", "labels": [{"name": "severity", "value": "critical"}, {"name": "suite", "value": "Test_Application"}, {"name": "subSuite", "value": "Test_Application"}, {"name": "host", "value": "LAPTOP-74FS1CKE"}, {"name": "thread", "value": "13140-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_Application"}]}